name: Forecast Weather
on:
  schedule:
    - cron: "40 11 * * *" # 06:00 AM KST
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Forecast Weather
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Run Scripts
        run: make forecast
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
